prometheus-rancher-exporter:
  image: infinityworks/prometheus-rancher-exporter:latest
  environment:
    - CATTLE_ACCESS_KEY=F160DBC58F8323B5F0D0
    - CATTLE_SECRET_KEY=Y2bu45NeR51bo82GApu1Xz5wmJzKiSdvp3iidFF5
    - CATTLE_URL=http://10.11.22.2:8080/v2-beta
    - HIDE_SYS=true
  ports:
    - 9173:9173
prometheus:
  image: prom/prometheus:v1.7.1
  volumes:
    - "./prometheus:/etc/prometheus/"
  ports:
    - 9090:9090
  net: host
alertmanager:
  image: prom/alertmanager:v0.7.1
  ports:
    - 9093:9093
grafana:
  image: grafana/grafana:4.3.2
  ports:
    - 3000:3000
